DROP TABLE IF EXISTS BOOKS;

  CREATE TABLE BOOKS (
    id INT AUTO_INCREMENT  PRIMARY KEY,
    title VARCHAR(250) NOT NULL,
    author VARCHAR(250) NOT NULL,
    genre VARCHAR(250) NOT NULL
  );

  DROP TABLE IF EXISTS USERS;

  CREATE TABLE USERS (
    id INT AUTO_INCREMENT  PRIMARY KEY,
    user VARCHAR(250) NOT NULL,
    password VARCHAR(250) NOT NULL,
    role VARCHAR(250) NOT NULL,
    email VARCHAR(250) NOT NULL
  );